###
# Gets all workplace categories added to a license
GET https://{{$dotenv apidomain}}/v1/workplace_categories HTTP/1.1
Authorization: Bearer {{$dotenv token}}

###
# Get workplace category members
@workplace_category_get_members_id=18
GET https://{{$dotenv apidomain}}/v1/workplace_categories/{{workplace_category_get_members_id}}/users HTTP/1.1
Authorization: Bearer {{$dotenv token}}

###
# Create a new workplace category to a license
#
# Minimal
POST https://{{$dotenv apidomain}}/v1/workplace_categories HTTP/1.1
Authorization: Bearer {{$dotenv token}}
content-type: application/json

{
  "name": "apitest minimal create test 2"
}

###
# Create a new workplace category to a license
#
# Full
POST https://{{$dotenv apidomain}}/v1/workplace_categories HTTP/1.1
Authorization: Bearer {{$dotenv token}}
content-type: application/json

{
  "name": "apitest full create test 1",
  "age": "18",
  "description": "workplace categories description goes here",
  "shift_info": "shift_info goes here"
}

###
# Update of workplace category
@workplace_category_update_id=18
PUT https://{{$dotenv apidomain}}/v1/workplace_categories/{{workplace_category_update_id}} HTTP/1.1
Authorization: Bearer {{$dotenv token}}
content-type: application/json

{
  "name": "apitest update category 2",
  "age": "19",
  "description": "workplace categories description goes here",
  "shift_info": "shift_info goes here"
}

###
# Delete workplace category
@workplace_category_delete_id=18
DELETE https://{{$dotenv apidomain}}/v1/workplace_categories/{{workplace_category_delete_id}} HTTP/1.1
Authorization: Bearer {{$dotenv token}}
