@event_id = {{$dotenv event_id}}

###
# Get all members from a specific workplace
@get_workplace_users_id=22
GET https://api.crewnet.dk/v1/events/{{event_id}}/workplaces/{{get_workplace_users_id}}/users HTTP/1.1
Authorization: Bearer {{$dotenv token}}

###
# Add a user to a workplace
@post_workplace_users_id=22
# Mads
@user_id=23168
POST https://api.crewnet.dk/v1/events/{{event_id}}/workplaces/{{post_workplace_users_id}}/users HTTP/1.1
Authorization: Bearer {{$dotenv token}}
content-type: application/json

{
    "user_id": {{user_id}}
}

###
# Remove a user from a workplace
@workplace_id=22
# Mads
@user_id=23168
DELETE https://api.crewnet.dk/v1/events/{{event_id}}/workplaces/{{workplace_id}}/users/{{user_id}} HTTP/1.1
Authorization: Bearer {{$dotenv token}}
