@nonce = {{$timestamp}}
# Spejdernes Lejr test
@event_id = {{$dotenv event_id}}

###
# Add workplace to event

# Event association test
@workplace_id=36
POST https://api.crewnet.dk/v1/events/{{event_id}}/workplaces
Authorization: Bearer {{$dotenv token}}

{
  "workplace_id": {{workplace_id}},
  "helper_need": 10
}

###
# Remove workplace from event

# Event association test
@workplace_id=36
DELETE https://api.crewnet.dk/v1/events/{{event_id}}/workplaces/{{workplace_id}}
Authorization: Bearer {{$dotenv token}}
