@event_id = {{$dotenv event_id}}
###
# Get all workplaces from a specific event
GET https://api.crewnet.dk/v1/workplaces?event_id={{event_id}} HTTP/1.1
Authorization: Bearer {{$dotenv token}}
content-type: application/json

###
# Create a new workspace in a specific event
POST https://api.crewnet.dk/v1/workplaces?event_workplace={{event_id}} HTTP/1.1
Authorization: Bearer {{$dotenv token}}
content-type: application/json

{
  "name": "Test workplace 1"
}

###
# Update a workplace
@put_workplace_id=22
PUT https://api.crewnet.dk/v1/workplaces/{{put_workplace_id}} HTTP/1.1
Authorization: Bearer {{$dotenv token}}
content-type: application/json

{
    "id": 22,
    "name": "Tilgængelighedstest",
    "workplace_category_id": null,
    "age": 1,
    "allow_create_happening": false,
    "allow_comment": false,
    "helper_need": 1
}

###
# Delete a workplace
@delete_workplace_id=35
DELETE https://api.crewnet.dk/v1/workplaces/{{delete_workplace_id}} HTTP/1.1
Authorization: Bearer {{$dotenv token}}
